version: "3"
services:
  tdd_word_filter:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: tdd_word_filter-image
    container_name: tdd_word_filter-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
